<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Divine</AssemblyName>
    <RootNamespace>Divine</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <VintageStoryInstall Condition="'$(VintageStoryInstall)' == ''">C:\Program Files\Vintage Story</VintageStoryInstall>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VintageStoryInstall)\VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>$(VintageStoryInstall)\VintagestoryLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
